# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('dynamic_scraper', '0026_auto_20171217_1634'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название гильдии')),
                ('url', models.URLField(verbose_name='Ссылка на профиль')),
                ('scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper')),
                ('scraper_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
            },
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='')),
                ('nickname', models.CharField(max_length=64, verbose_name='')),
                ('profile_url', models.URLField(verbose_name='Ссылка на профиль')),
                ('galactic_power', models.FloatField(verbose_name='')),
                ('collection_score', models.FloatField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
            },
        ),
    ]
