# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_guildmember_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildmember',
            name='checker_runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime'),
        ),
    ]
