# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('unit_type', models.PositiveSmallIntegerField(choices=[(0, 'Character'), (1, 'Ship')], default=0, verbose_name='Unit type')),
                ('checker_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('unit_type', models.PositiveSmallIntegerField(choices=[(0, 'Character'), (1, 'Ship')], default=1, verbose_name='Unit type')),
                ('checker_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
            options={
                'verbose_name': 'Корабль',
                'verbose_name_plural': 'Корабли',
            },
        ),
        migrations.CreateModel(
            name='UnitPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('url', models.URLField()),
                ('unit_type', models.PositiveSmallIntegerField(choices=[(0, 'Character'), (1, 'Ship')], default=0, verbose_name='Unit type')),
                ('scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper')),
                ('scraper_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
            options={
                'verbose_name': 'Unit page',
                'verbose_name_plural': 'Unit pages',
            },
        ),
        migrations.AddField(
            model_name='ship',
            name='unit_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.UnitPage'),
        ),
        migrations.AddField(
            model_name='character',
            name='unit_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.UnitPage'),
        ),
    ]
